"""Добавить corp-humor в таблицу скиллов AGENTS.md."""
import pathlib

DESCRIPTION = "add corp-humor skill — shared primate jokes generated by Приор"

OLD = ("| `corp-greeting` | `/shared/skills/corp-greeting/SKILL.md` "
       "| Приветствие при старте сессии — каждый раз новое |")
NEW = (OLD + "\n"
       "| `corp-humor` | `/shared/skills/corp-humor/SKILL.md` "
       "| Пул приматных шуток от Приора — использовать органично, между делом |")

def apply(workspace: pathlib.Path):
    p = workspace / "AGENTS.md"
    if not p.exists():
        return
    text = p.read_text()
    if OLD in text and "corp-humor" not in text:
        p.write_text(text.replace(OLD, NEW))
